# Generated by Django 3.2.25 on 2026-05-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0003_auto_20260422_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
