# Generated by Django 3.2.25 on 2026-05-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0004_address_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='addresses',
            field=models.ManyToManyField(to='bookmodule.Address'),
        ),
    ]
