# Generated by Django 3.2.25 on 2026-05-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0005_auto_20260517_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='students/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmodule.student')),
            ],
        ),
    ]
